config/routes.rb
Swarm::Application.routes.draw do |map|

  root :to => "home#index"
  match 'about', :to => "home#about", :as => 'about'
  match 'genre/:genre', :to => "home#index", :as => 'genre_search'
  
  resources :movies do
    member do
      get :id
    end
  end

  resources :torrents do
    collection do
      put :verify
      get :find_movie
    end
  end

end

app/models/torrent.rb
class Torrent < ActiveRecord::Base
  validates_presence_of :name
  validates_uniqueness_of :name, :case_sensitive => false

  belongs_to :movie
  has_many :torrent_stats do
    def latest
      find(:first, :order => 'created_at DESC')
    end  
  end  
  
  after_create :associate_with_movie
  
  def stats
    torrent_stats
  end
  
  def cleaned_name
    ToName.to_name(name)
  end  
  
  def movie?
    !movie.blank?
  end

  private
    def associate_with_movie
      return unless movie.nil?
      name_info = cleaned_name
      if name_info.year.blank?
        self.movie = Movie.find_by_name(name_info.name)
      else
        self.movie = Movie.find_by_name_and_year(name_info.name, name_info.year)
      end
      
      unless movie
        logger.info "Searching imdb for #{name_info.name} (#{name_info.year})"
        imdb_id = YayImdbs.search_for_imdb_id(name_info.name, name_info.year)
        if imdb_id.present?
          logger.info "Found imdb id #{imdb_id} for #{name_info.name} (#{name_info.year})"
          self.movie = Movie.find_or_create_by_imdb_id(imdb_id)
        else
          logger.warn "Couldn't find imdb id for #{name_info.name} (#{name_info.year})"
        end
      end  
      save!
    end  
end

app/controllers/torrents_controller.rb
class TorrentsController < ApplicationController
  layout 'no_sidebar'

  def index
    @torrents = Torrent.includes(:movie).order('created_at DESC')
    unless params[:search_torrents].blank?
      @torrents = @torrents.where('name like ?', "%#{params[:search_torrents]}%")
    else
      @torrents = @torrents.where(:verified => false)
    end
    @torrents = @torrents.paginate(:page => params[:page], :per_page => 30)

    render 'index'
  end

  def verify
      params[:verify].each do |index, verify_param|
        next unless verify_param[:verified] == '1'
        verify_param[:movie_id] = Movie.find_or_create_by_imdb_id(verify_param[:imdb_id]).id if verify_param[:movie_id].to_i < 1
        Torrent.find(verify_param[:torrent_id]).update_attributes!(:movie_id => verify_param[:movie_id], 
                                                                   :verified => true)
      end
      redirect_to(:action => :index)
  end

  def find_movie
    render :json => 
      YayImdbs.search_imdb(params[:new_movie_title]).collect { |movie_info|
        movie_info.merge(:movie_id => (Movie.find_by_imdb_id(movie_info[:imdb_id]).id rescue nil))
      }
  end
end

app/views/torrents/index.html.erb
<% content_for :head do %>
  <%= javascript_include_tag 'torrents' %>
<% end %>

<% content_for :main_title do %>
  Verify Torrents
<% end %>

<% content_for :sidebar_title do %>
  <%= form_tag(torrents_path, :method => "get") do %>
    <%= label_tag "search_torrents", "Search Torrents", :class => 'hidden' %> 
    <input type="search" name="search_torrents" id="search_torrents" value="<%= params[:search_torrents] %>" style="float: left;"/>
    <%= submit_tag "Search", :class => "action-button", :id => 'search-torrents-button' %>
  <% end %>
<% end %>

<% unless @torrents.blank? %>
  <%= form_tag(verify_torrents_path, :method => "put") do %>
    <div class="post" style="margin-bottom: 10px;">
        <table id="verify-torrents-table" class="rounded-table">
          <thead>
            <tr>
              <th></th>
              <th>Torrent</th>
              <th>Movie</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @torrents.each_with_index do |torrent, index| %>
              <tr id="match_row_for_<%= torrent.id %>">
                <td>
                  <%= label_tag "verify_torrent_#{torrent.id}", "Verify #{torrent.name}", :class => 'hidden' %> 
                  <%= check_box_tag "verify[#{index}][verified]", "1", false, 
                      {:id => "verify_torrent_#{torrent.id}"}.merge(torrent.movie? ? {} : {:disabled => true}) %>
                  <%= hidden_field_tag "verify[#{index}][torrent_id]", torrent.id, :id => "torrent_id_for_#{torrent.id}" %>
                  <%= hidden_field_tag "verify[#{index}][imdb_id]", '', :id => "imdb_id_for_#{torrent.id}" %>
                  <%= hidden_field_tag "verify[#{index}][movie_id]", torrent.movie? ? torrent.movie.id : 0, 
                        :id => "movie_id_for_#{torrent.id}" %>
                </td>
                <td><div class="torrent-name-container"><%= torrent.name %></div></td>
                <td id="link_to_movie_for_<%= torrent.id %>"><%= link_to(torrent.movie.display_name, movie_path(torrent.movie), {:target => '_blank'}) if torrent.movie %></td>
                <td>
                  <input type="button" value="Change" class="action-button change-movie" data-movie-name="<%= ToName.to_name(torrent.name).name %>" data-torrent-id="<%= torrent.id %>"/>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div id="torrent-verify-buttons">
        <input id="select-all-checkboxes" type="button" value="Select All" class="action-button" />
        <%= submit_tag "Verify", :class => "action-button", :id => 'verify-torrents-button' %>
      </div>
  <% end %>

  <%= will_paginate @torrents, :inner_window => 1, :outer_window => 1 %>

<% else %>
  No un-verifed torrents.
<% end %>

<div id="change-movie-dialog" title="Change Torrent's Movie">
	<form id="change-movie-form">
    <label for="new_movie_title">Movie Name:</label>
    <input type="text" name="new_movie_title" id="new_movie_title" class="text ui-widget-content ui-corner-all" />
    <input id="change-movie-search-button" type="button" value="Search" class="action-button" />
    <div id="change-movie-loading-indicator" class="loading-indicator loading-indicator-active" style="display:none"></div>
  </form>
  <hr/>
  <table id="change-movie-table" class="rounded-table" style="display:none">
    <thead>
      <tr>
        <th>Movie</th>
        <th>Year</th>
        <th>Swarm Page</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
    </tbody>
  </table>
</div>