config/routes.rb
Swarm::Application.routes.draw do |map|

  root :to => "home#index"
  match 'about', :to => "home#about", :as => 'about'
  match 'genre/:genre', :to => "home#index", :as => 'genre_search'
  
  resources :movies do
    member do
      get :id
    end
  end

  resources :torrents do
    collection do
      put :verify
      get :find_movie
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
	<title><%= content_for?(:title) ? (yield :title) : 'Swarms' %></title>
	<%= stylesheet_link_tag 'theme' %>
	<%= stylesheet_link_tag 'flick/jquery-ui-1.8.4.custom' %>
	<!--[if lt IE 8]>
		<%= stylesheet_link_tag 'theme_ie' %>
	<![endif]-->
	<%= stylesheet_link_tag 'style' %>
	<%= javascript_include_tag :defaults %>
	<%= javascript_include_tag 'jquery.tooltip' %>
  <%= javascript_include_tag 'jquery-ui-1.8.4.custom.min' %>

  <%= javascript_include_tag 'jquery.cookie' %>
	<%= javascript_include_tag 'custom-download-link' %>

	<%= csrf_meta_tag %>

  <link href='http://fonts.googleapis.com/css?family=Vollkorn' rel='stylesheet' type='text/css'>
  <link  href="http://fonts.googleapis.com/css?family=Lobster:regular" rel="stylesheet" type="text/css" >

  <script type="text/javascript" charset="utf-8"> 
    $(document).ready(function(){
        $(".tooltip").simpletooltip();
        $("#configure-download-link").click(function(){
          openCustomLinkDialog();
          return false;
        });
    });
  </script> 

	<%= yield :head %>
</head>

<body>
	<div id="pg-nav-bg"> 
		<div class="wrapper clear"> 
			<div id="pg-nav"> 
				<ul class="nav"> 
					<li class="page_item <%= 'current_page_item' if current_page?(root_path) %>"><%= link_to "Home", root_path %></li> 
          <li class="page_item"><a href="#" id="configure-download-link">Settings</a></li> 
					<li class="page_item <%= 'current_page_item' if current_page?(about_path) %>"><%= link_to "About", about_path %></li> 
				</ul> 
			</div><!--end page-navigation--> 
		</div><!--end wrapper--> 
	</div><!--end page-navigation-bg--> 
		
	<div class="wrapper big"> 
		<div id="header" class="clear"> 
			<div class="logo"> 
				<h2 id="title"><%= link_to "Swarms", root_path %></h2>				
				<div id="description"> 
					Movie torrent statistics			
				</div><!--end description--> 
			</div><!--end logo--> 
			
		</div><!--end header--> 
			
		<div id="main-top"> 
      <h1><%= yield :main_title %></h1>
      <div id="loading-indicator"></div> 
			<div class="subscribe"> 
				<h5><%= yield :sidebar_title %></h5> 
			</div>	
		</div> 
				
		<div id="main" class="clear"> 
			<div id="content">
				<%= yield %>
			</div><!--end content--> 
			<div id="sidebar"> 
				<%= yield :sidebar %>
			</div><!--end sidebar-->	
		</div><!--end main--> 
	
	<div id="main-bottom"></div> 
</div><!--end wrapper--> 


<div id="footer"> 
	<div class="wrapper clear"> 
    <div id="footer-genres" class="footer-column"> 
      <ul> 
        <li class="widget"> 
        <h2>Genres</h2> 
        <ul class="genres-list">
          <% @genres.each do |genre| %>
            <li class="page_item genres-list-item">
              <%= link_to genre.name, genre_search_path(CGI.escape(genre.name.downcase)) %>
            </li> 
        <% end %>
        </ul>
        </li>
      </ul>
    </div> 
		<div id="footer-search" class="footer-column"> 
			<h2>Search</h2> 
        <%= form_tag(root_path, :method => :get, :id => 'search_form') do %>
					<input type="search"	name="q" id="q" class="search"/> 
					<input type="submit" id="searchsubmit" value="Search" class="action-button"/> 
        <% end %> 
		</div> 
	</div><!--end wrapper--> 
</div><!--end footer--> 

<div id="copyright" class="wrapper"> 
	<p class="credit"><a href="http://thethemefoundry.com/traction/">Traction Theme</a> by <a href="http://thethemefoundry.com">The Theme Foundry</a></p> 
	<p>Swarms | 0-0-1 | developed by <a href="mailto:cavenaghweb@hotmail.com">Sam Cavenagh</a></p> 
</div><!--end copyright-->

<%= render :partial => '/shared/download_link_dialog' %>

</body>
</html>

app/views/layouts/base.html.erb
<!DOCTYPE html>
<html>

<head>
	<title><%= content_for?(:title) ? (yield :title) : 'Swarms' %></title>
	<%= stylesheet_link_tag 'theme' %>
	<%= stylesheet_link_tag 'flick/jquery-ui-1.8.4.custom' %>
	<!--[if lt IE 8]>
		<%= stylesheet_link_tag 'theme_ie' %>
	<![endif]-->
	<%= stylesheet_link_tag 'style' %>
	<%= javascript_include_tag :defaults %>
	<%= javascript_include_tag 'jquery.tooltip' %>
  <%= javascript_include_tag 'jquery-ui-1.8.4.custom.min' %>

  <%= javascript_include_tag 'jquery.cookie' %>
	<%= javascript_include_tag 'custom-download-link' %>

	<%= csrf_meta_tag %>

  <link href='http://fonts.googleapis.com/css?family=Vollkorn' rel='stylesheet' type='text/css'>
  <link  href="http://fonts.googleapis.com/css?family=Lobster:regular" rel="stylesheet" type="text/css" >

  <script type="text/javascript" charset="utf-8"> 
    $(document).ready(function(){
        $(".tooltip").simpletooltip();
        $("#configure-download-link").click(function(){
          openCustomLinkDialog();
          return false;
        });
    });
  </script> 

	<%= yield :head %>
</head>

<body>
	<div id="pg-nav-bg"> 
		<div class="wrapper clear"> 
			<div id="pg-nav"> 
				<ul class="nav"> 
					<li class="page_item <%= 'current_page_item' if current_page?(root_path) %>"><%= link_to "Home", root_path %></li> 
          <li class="page_item"><a href="#" id="configure-download-link">Settings</a></li> 
					<li class="page_item <%= 'current_page_item' if current_page?(about_path) %>"><%= link_to "About", about_path %></li> 
				</ul> 
			</div><!--end page-navigation--> 
		</div><!--end wrapper--> 
	</div><!--end page-navigation-bg--> 
		
	<div class="wrapper big"> 
		<div id="header" class="clear"> 
			<div class="logo"> 
				<h2 id="title"><%= link_to "Swarms", root_path %></h2>				
				<div id="description"> 
					Movie torrent statistics			
				</div><!--end description--> 
			</div><!--end logo--> 
			
		</div><!--end header--> 
			
		<div id="main-top"> 
      <h1><%= yield :main_title %></h1>
      <div id="loading-indicator"></div> 
			<div class="subscribe"> 
				<h5><%= yield :sidebar_title %></h5> 
			</div>	
		</div> 
				
		<div id="main" class="clear"> 
      <%= yield :main %>
		</div><!--end main--> 
	
	<div id="main-bottom"></div> 
</div><!--end wrapper--> 


<div id="footer"> 
	<div class="wrapper clear"> 
    <div id="footer-genres" class="footer-column"> 
      <ul> 
        <li class="widget"> 
        <h2>Genres</h2> 
        <ul class="genres-list">
          <% @genres.each do |genre| %>
            <li class="page_item genres-list-item">
              <%= link_to genre.name, genre_search_path(CGI.escape(genre.name.downcase)) %>
            </li> 
        <% end %>
        </ul>
        </li>
      </ul>
    </div> 
		<div id="footer-search" class="footer-column"> 
			<h2>Search</h2> 
        <%= form_tag(root_path, :method => :get, :id => 'search_form') do %>
					<input type="search"	name="q" id="q" class="search"/> 
					<input type="submit" id="searchsubmit" value="Search" class="action-button"/> 
        <% end %> 
		</div> 
	</div><!--end wrapper--> 
</div><!--end footer--> 

<div id="copyright" class="wrapper"> 
	<p class="credit"><a href="http://thethemefoundry.com/traction/">Traction Theme</a> by <a href="http://thethemefoundry.com">The Theme Foundry</a></p> 
	<p>Swarms | 0-0-1 | developed by <a href="mailto:cavenaghweb@hotmail.com">Sam Cavenagh</a></p> 
</div><!--end copyright-->

<%= render :partial => '/shared/download_link_dialog' %>

</body>
</html>

app/views/layouts/no_sidebar.html.erb
<% content_for :main do %>
			<div id="content" class="no-sidebar">
				<%= yield %>
			</div><!--end content--> 
<% end %>
<%= render :file => 'layouts/base' %>